// PHI label mapping and clinical-text lexicons shared by the entity-detection
// and temporal modules. All bindings here are read-only lookup tables built
// once at module init — nothing here is mutated after this file finishes
// evaluating.

export const phiLabelMap = {
  HCW: "PROVIDER NAME",
  PATIENT: "PATIENT NAME",
  CONTACT: "CONTACT NAME",
  DOCTOR: "PROVIDER NAME",
  PHYSICIAN: "PROVIDER NAME",
  PROVIDER: "PROVIDER NAME",
  PERSON: "NAME",
  PER: "NAME",
  NAME: "NAME",
  FIRST_NAME: "NAME",
  LAST_NAME: "NAME",
  EMAIL_ADDRESS: "EMAIL",
  EMAIL: "EMAIL",
  PHONE_NUMBER: "PHONE",
  PHONE: "PHONE",
  FAX_NUMBER: "PHONE",
  URL: "URL",
  IP_ADDRESS: "IP",
  IPV4: "IP",
  IPV6: "IP",
  DATE_TIME: "DATE",
  DATE: "DATE",
  DATE_OF_BIRTH: "DOB",
  DOB: "DOB",
  "DOB REDACTED": "DOB",
  MEDICAL_RECORD: "MRN",
  MEDICAL_RECORD_NUMBER: "MRN",
  MRN: "MRN",
  CSN: "ENCOUNTER ID",
  FIN: "ENCOUNTER ID",
  HAR: "ENCOUNTER ID",
  ACCOUNT_NUMBER: "ID",
  UNIQUE_ID: "ID",
  CUSTOMER_ID: "ID",
  ID_CARD: "ID",
  INSURANCE_NUMBER: "ID",
  HEALTH_PLAN_BENEFICIARY_NUMBER: "ID",
  SSN: "ID",
  US_SSN: "ID",
  TAX_ID: "ID",
  DRIVER_LICENSE: "ID",
  US_DRIVER_LICENSE: "ID",
  US_PASSPORT: "ID",
  PASSPORT_NUMBER: "ID",
  STREET_ADDRESS: "ADDRESS",
  ADDRESS: "ADDRESS",
  CITY: "LOCATION",
  STATE: "LOCATION",
  COUNTY: "LOCATION",
  COUNTRY: "LOCATION",
  POSTCODE: "LOCATION",
  ZIPCODE: "LOCATION",
  ZIP: "LOCATION",
  LOCATION: "LOCATION",
  HOSPITAL: "FACILITY",
  FACILITY: "FACILITY",
  ORGANIZATION: "ORGANIZATION",
  COMPANY_NAME: "ORGANIZATION",
  VENDOR: "ORGANIZATION",
  ROOM: "ROOM",
  UNIT: "ROOM",
  BED: "ROOM",
  BIOMETRIC: "ID",
  VEHICLE: "ID",
  VEHICLE_ID: "ID",
  VEHICLE_IDENTIFIER: "ID",
  DEVICE_ID: "ID",
  DEVICE_IDENTIFIER: "ID",
  MAC_ADDRESS: "ID",
  IMEI: "ID",
  GIVENNAME: "NAME",
  SURNAME: "NAME",
  AGE: "AGE",
  CITY: "LOCATION",
  STATE: "LOCATION",
  COUNTY: "LOCATION",
  COUNTRY: "LOCATION",
  STREET: "ADDRESS",
  ZIPCODE: "LOCATION",
  BUILDINGNUMBER: "ADDRESS",
  TELEPHONENUM: "PHONE",
  TITLE: "NAME",
  TIME: "DATE",
  USERNAME: "ID",
  PASSWORD: "ID",
  ACCOUNTNUMBER: "ID",
  IDCARDNUMBER: "ID",
  SOCIALNUMBER: "ID",
  STAFF: "PROVIDER NAME",
  HOSP: "FACILITY",
  PATORG: "ORGANIZATION",
  OTHERPHI: "PHI"
};

export const nameEntityLabels = new Set(["NAME", "PATIENT NAME", "PROVIDER NAME", "CONTACT NAME"]);

export const nonNameClinicalPhrases = new Set([
  "basic information", "chief complaint", "principal problem", "active problems", "resolved problems",
  "synthetic demo soap note",
  "atypical chest", "atypical chest pain", "chronic pain", "home escitalopram", "heart healthy",
  "chest pain", "shortness of breath", "present illness", "history of present illness",
  "hpi", "pmh", "psh", "ros", "a/p", "soap", "cc", "ed", "icu", "dka", "aki", "ckd", "chf",
  "copd", "cad", "t1dm", "t2dm", "cbc", "bmp", "cmp", "tsh", "a1c",
  "last reading", "hour range", "pulmonary toilet", "bowel management", "fall risk", "suicide risk",
  "elopement risk", "elopmement risk", "daily labs", "immature grans", "provider referral",
  "abnormal labs", "summary situational", "awareness action",
  "general neurology", "history problem", "past medical", "past medical history", "surgical history",
  "family history", "social history", "home meds", "home medications", "current medications",
  "current medication", "prior medications", "inpatient medications", "scheduled medications",
  "prn medications", "infusion medications", "hospital course", "interval history", "progress note",
  "discharge summary", "admission note", "transfer summary", "operative note", "procedure note",
  "radiology report", "pathology report", "microbiology results", "blood culture", "urine culture",
  "respiratory culture", "assessment plan", "assessment and plan", "physical exam", "focused exam",
  "review systems", "review of systems", "allergies", "vital signs", "lab results", "laboratory results",
  "consult note", "endocrinology consult", "cardiology consult", "neurology consult",
  "nephrology consult", "pulmonology consult", "infectious disease consult", "infectious disease",
  "gastroenterology consult", "treatment team", "scheduled meds", "current inpatient", "vital sign",
  "heart rate", "output summary", "basic metabolic", "complete blood", "reticulated platelets",
  "plt morphology", "normal absolute", "platelet count", "absolute neutrophils", "absolute lymphocytes",
  "atypical lymphocytes", "absolute monocytes", "absolute basophils", "absolute eosinophils",
  "burr cells", "anion gap", "see comment", "toxic granulation", "total protein", "bilirubin total",
  "alk phos", "base excess", "phosphorus level", "iron studies", "thyroid studies", "warfarin sodium",
  "insulin glargine", "insulin lispro", "insulin regular", "metformin hydrochloride", "heparin infusion",
  "vancomycin trough", "blood glucose", "urine output", "intake output", "mental status",
  "oxygen saturation", "respiratory rate", "blood pressure", "temperature maximum", "temperature minimum",
  "mean arterial", "arterial pressure", "encephalopathy diabetes", "diabetes mellitus", "acute kidney",
  "kidney injury", "diabetic ketoacidosis", "autoimmune hypothyroidism", "autoimmune thyroiditis",
  "sick day management", "poor sick day management", "sick day education", "sick day protocols",
  "renal function", "heart failure", "respiratory failure", "altered mental",
  "general medicine", "type 1 diabetes mellitus", "type 2 diabetes mellitus", "free t4",
  "beta hydroxybutyrate", "beta-hydroxybutyrate",
  "memorial day", "memorial day weekend",
  "fetal heart", "heart auscultation", "fetal heart auscultation",
  "asthma management", "childhood asthma", "childhood asthma management",
  "asthma clinic", "allergy and asthma clinic", "asthma associates",
  "heart institute", "heart association", "chest x-ray",
  "heart failure exacerbation", "congestive heart failure",
  "congestive heart failure exacerbation", "upper extremities",
  "acute bronchitis", "essential hypertension",
  "mild intermittent asthma", "allergy and asthma",
  "allergy clinic", "asthma center",
  "insulin instructions", "lisinopril instructions",
  "insulin humulin", "insulin humulin instructions",
  "abuse-deterrent oxycodone", "abuse-deterrent oxycodone hydrochloride",
  "oxycodone hydrochloride", "extended release",
  "dialysis center", "dialysis clinic",
  "heart rate", "heart institute", "heart association",
  "anemia clinic", "anemia management",
  // ── Phrases found in remaining 93 bugs ──
  "anemia secondary", "anemia due", "anemia related", "symptomatic anemia",
  "organ transplant", "serum creatinine", "chest tightness",
  "chronic heart disease", "ischemic heart disease",
  "cardiovascular risk monitoring", "cardiovascular monitoring",
  "respiratory support", "asthma follow-up", "asthma follow up",
  "dialysis consideration", "dialysis optimization", "dialysis maintenance",
  "dialysis appointments", "dialysis procedures", "dialysis procedure",
  "recent dialysis", "dialysis procedure conducted",
  "transplant procedures", "transplant nephrologist",
  "renal dialysis", "renal dialysis procedures", "renal dialysis monitoring",
  "renal dialysis session", "renal dialysis procedures performed",
  "manage hypertension", "adjust dialysis", "adjust dialysis parameters",
  "insulin regimen", "insulin isophane", "calcium carbonate",
  "monitor cbc", "monitor hemoglobin",
  "furosemide administration", "adjust furosemide", "adjust lisinopril",
  "ibuprofen prescription", "sodium fluoride",
  "children's acetaminophen", "pediatric asthma",
  "prescribed penicillin v potassium",
  "chronic obstructive bronchitis",
  "severe acute respiratory syndrome coronavirus",
  "sodium fluoride gel", "sodium fluoride oral gel",
  "encounter type", "encounter for",
]);

export const nonNameClinicalWords = new Set([
  "abdomen", "abdominal", "absolute", "acetaminophen", "action", "active", "activity", "acute", "admission",
  "abnormal", "albumin", "alk", "alkaline", "allergies", "alt", "and", "anion", "anesthesia", "antibiotic",
  "anticoagulation", "arterial", "assessment", "ast", "atypical", "autoimmune", "awareness", "basophils", "base", "basic",
  "beta", "bicarbonate", "bilirubin", "blood", "bladder", "bowel", "brain", "bun", "burr",
  "calcium", "cardiac", "cardiology", "cardiovascular", "catheter", "cbc", "cells", "cervical",
  "chloride", "chief", "clinic", "cloudy", "coagulation", "code", "comment", "complaint", "complete",
  "consult", "coordination", "count", "course", "cranial", "creatinine", "critical", "culture",
  "current", "daily", "decreased", "dermatology", "diabetes", "diagnoses", "diagnosis", "diet", "differential",
  "dimer", "discharge", "discomfort", "drain", "dvt", "edema", "elevated", "elopement", "elopmement",
  "emergency", "encephalopathy", "endocrine", "endocrinology", "eosinophils", "escitalopram",
  "esr", "exam", "excess", "failure", "fall", "family", "ferritin", "fibrinogen", "follow",
  "free", "gap", "gastroenterology", "general", "glucose", "gram", "granulation", "granulocytes",
  "grans", "gu", "hba1c", "hct", "healthy", "heart", "hematocrit", "hematology",
  "hemoglobin", "hepatology", "hgb", "high", "history", "home", "hospital", "hospitalist", "hour",
  "hydroxybutyrate", "hyperthyroidism", "hypothyroidism", "imaging", "immature", "impression",
  "infectious", "information", "injury",
  "inpatient", "intact", "intake", "iron", "ketoacidosis", "ketones", "kidney", "lab", "laboratory",
  "labs", "lactate",
  "lactic", "last", "level", "line", "lipase", "liver", "low", "lumbar", "lung", "lungs", "lymphocytes",
  "magnesium", "management", "maximum", "mean", "medical", "medication", "medications", "medicine", "meds",
  "mental", "microbiology", "minimum", "monocytes", "morphology", "motor", "musculoskeletal",
  "nausea", "nephrology", "nerve", "neuro", "neurologic", "neurology", "neurosurgery", "neutrophils",
  "nightly", "normal",
  "note", "objective", "obstetrics", "oncology", "operative", "orthopedics", "outpatient", "output",
  "palliative", "pathology", "past", "pco2", "pediatrics", "ph", "pharmacy", "phos", "phosphatase",
  "phosphate", "phosphorus", "physical", "platelet", "platelets", "plt", "po2", "polydipsia",
  "polyuria", "potassium",
  "precautions", "principal", "prn", "problem", "problems", "procedure", "procalcitonin", "progress",
  "protein", "psychiatry", "pt", "ptt", "pulmonary", "pulmonology", "radiology", "range", "rare", "rate",
  "rbc", "reading", "red", "referral", "reflex", "renal", "report", "resolved", "respiratory",
  "reticulated", "reticulocyte",
  "review", "rheumatology", "risk", "saturation", "sc", "scheduled", "schistocytes", "see", "sensory", "severe",
  "sign", "signs", "situational", "sodium", "social", "spinal", "spine", "sputum", "stain", "status",
  "subcutaneous", "subjective",
  "studies", "suicide", "summary", "surgery", "surgical", "systems", "t4", "team", "temperature", "therapy",
  // ── Words found missing by 3,381-note audit ──
  "fetal", "auscultation", "asthma", "allergy", "allergies", "x-ray", "xray",
  "congestive", "exacerbation", "childhood", "institute", "association",
  "extremities", "bronchitis", "sinusitis", "pneumonia", "hepatitis",
  "intermittent", "mild", "moderate", "severe", "upper", "lower",
  "endoscopy", "colonoscopy", "transplant", "dialysis", "ecg", "ekg",
  "hyperlipidemia", "cardiovascular", "neurological", "respiratory",
  "penicillin", "amoxicillin", "ibuprofen", "sertraline", "albuterol",
  "hydrochlorothiazide", "furosemide", "lisinopril", "gabapentin",
  "oxycodone", "tramadol", "morphine", "codeine", "hydromorphone",
  "oxycontin", "percocet", "vicodin", "norco", "ultram",
  "spironolactone", "eplerenone", "digoxin", "amiodarone",
  "verapamil", "diltiazem", "nifedipine", "nitroglycerin",
  "calcium", "magnesium", "phosphorus", "potassium", "sodium", "chloride",
  "hemoglobin", "hematocrit", "creatinine", "bicarbonate", "lactate",
  "troponin", "ferritin", "transferrin", "bilirubin", "albumin",
  "globulin", "alkaline", "phosphatase", "amylase", "lipase",
  "glucose", "insulin", "glucagon", "cortisol", "thyroxine",
  "estrogen", "testosterone", "progesterone", "prolactin",
  "antibody", "antigen", "antibodies", "immunoglobulin",
  "a1c", "hba1c", "tsh", "t4", "t3", "bun", "egfr", "inr", "pt", "ptt",
  "ldl", "hdl", "vldl", "triglycerides", "cholesterol", "lipid",
  "urinalysis", "culture", "sensitivity", "gram", "stain",
  "hypertension", "hypotension", "tachycardia", "bradycardia",
  "arrhythmia", "palpitations", "murmur", "gallop", "rub",
  "crackles", "rales", "rhonchi", "wheezing", "wheezes",
  "tenderness", "guarding", "rebound", "rigidity", "distension",
  "edema", "erythema", "swelling", "inflammation", "infection",
  "hemorrhage", "bleeding", "clotting", "coagulation", "thrombosis",
  "embolism", "infarction", "ischemia", "necrosis", "apoptosis",
  "hyperplasia", "dysplasia", "neoplasia", "malignancy", "metastasis",
  "carcinoma", "sarcoma", "lymphoma", "leukemia", "melanoma",
  "adenoma", "papilloma", "fibroma", "lipoma", "angioma",
  // ── Clinical modifier words ──
  "acute", "chronic", "probable", "possible", "likely", "unlikely",
  "suspected", "occasional", "intermittent", "persistent", "recurrent",
  "ischemic", "hemorrhagic", "traumatic", "infectious", "inflammatory",
  "autoimmune", "idiopathic", "iatrogenic", "congenital", "acquired",
  "community-acquired", "hospital-acquired", "ventilator-associated",
  "viral", "bacterial", "fungal", "parasitic", "mycobacterial",
  "malignant", "benign", "metastatic", "localized", "advanced",
  "compensated", "decompensated", "controlled", "uncontrolled",
  "stable", "unstable", "progressive", "resolving", "worsening",
  "exertional", "nocturnal", "orthopnea", "paroxysmal",
  "dyspnea", "syncope", "presyncope", "vertigo", "dizziness",
  "fatigue", "malaise", "anorexia", "weight loss", "weight gain",
  "fever", "chills", "rigors", "night sweats", "diaphoresis",
  // ── Words from remaining 93 edge cases ──
  "secondary", "symptomatic", "organ", "serum", "tightness",
  "risk", "monitoring", "monitor", "follow-up", "followup",
  "consideration", "optimization", "maintenance", "appointments",
  "appointment", "prescription", "regimen", "instructions",
  "encounter", "session", "sessions", "adjust", "initial",
  "pediatric", "obstructive", "fluoride", "carbonate",
  "isophane", "coronavirus", "copd", "ards", "sars",
  "performed", "conducted", "completed", "scheduled",
  "due", "related", "secondary", "primary", "initial",
  "sodium", "calcium", "potassium", "magnesium", "chloride",
  "children", "child", "adult", "adults", "pediatric",
  "prescribed", "continue", "discontinue", "adjust", "modified",
  "increased", "decreased", "reduced", "changed", "switched",
  "generic", "brand", "tablet", "tablets", "capsule", "capsules",
  "injection", "infusion", "solution", "suspension", "syrup",
  "cream", "ointment", "lotion", "gel", "patch", "patches",
  "spray", "inhaler", "nebulizer", "drops", "suppository",
  "dose", "dosage", "doses", "milligrams", "mg", "mcg", "grams",
  "units", "unit", "international", "iu", "meq", "milliequivalents",
  "daily", "weekly", "monthly", "hourly", "nightly",
  "before", "after", "with", "without", "during", "between",
  "baseline", "current", "previous", "prior", "recent",
  "ongoing", "planned", "scheduled", "anticipated",
  "asthma", "allergy", "allergies", "allergic", "sinusitis",
  "bronchitis", "pneumonia", "influenza", "covid", "covid-19",
  "hypertension", "hypotension", "tachycardia", "bradycardia",
  "arrhythmia", "palpitations", "murmur", "gallop", "rub",
  "crackles", "rales", "rhonchi", "wheezing", "wheezes",
  "tenderness", "guarding", "rebound", "rigidity", "distension",
  "edema", "erythema", "swelling", "inflammation", "infection",
  "hemorrhage", "bleeding", "clotting", "coagulation", "thrombosis",
  "embolism", "infarction", "ischemia", "necrosis", "apoptosis",
  "thoracic", "thyroid", "tibc", "toilet", "tone", "total", "toxic", "transfer", "transferrin", "trauma",
  "treatment", "triglycerides", "troponin", "tsh", "turbid", "ua", "unit", "urinary", "urine",
  "urology", "vascular", "vital", "vitals", "warfarin", "wbc", "white", "wound"
]);

export const commonFirstNames = new Set([
  "aaron", "abigail", "adam", "adrian", "alan", "albert", "alex", "alexander", "alexandra", "alice",
  "alicia", "allison", "amanda", "amber", "amy", "andrea", "andrew", "angela", "ann", "anna", "anne",
  "anthony", "antonio", "arthur", "ashley", "austin", "barbara", "benjamin", "betty", "beverly",
  "bill", "billy", "bobby", "bonnie", "brandon", "brenda", "brian", "brittany", "bruce", "bryan",
  "caleb", "carl", "carla", "carlos", "carol", "carolyn", "carrie", "catherine", "charles", "charlotte",
  "cheryl", "chris", "christina", "christine", "christopher", "cindy", "clara", "clarence", "connie",
  "craig", "crystal", "curtis", "cynthia", "dale", "dan", "daniel", "danielle", "david", "dawn",
  "deborah", "debra", "denise", "dennis", "diana", "diane", "donald", "donna", "doris", "dorothy",
  "douglas", "dylan", "earl", "edith", "edna", "edward", "elaine", "elizabeth", "ellen", "emily",
  "emma", "eric", "erica", "erin", "ernest", "ethan", "eugene", "evelyn", "florence", "frances",
  "frank", "fred", "gabriel", "gary", "george", "gerald", "gloria", "grace", "gregory", "hannah",
  "harold", "harry", "heather", "helen", "henry", "howard", "irene", "isabella", "jack", "jacob",
  "jacqueline", "james", "jamie", "jane", "janet", "janice", "jason", "jean", "jeffrey", "jennifer",
  "jeremy", "jerry", "jesse", "jessica", "jill", "jimmy", "joan", "joe", "john", "johnny", "jonathan",
  "jordan", "jose", "joseph", "joshua", "joyce", "juan", "judith", "judy", "julia", "julie", "justin",
  "karen", "katherine", "kathleen", "kathryn", "kathy", "kayla", "keith", "kelly", "kenneth", "kevin",
  "kim", "kimberly", "kyle", "larry", "laura", "lauren", "lawrence", "lee", "leslie", "lillian",
  "linda", "lisa", "logan", "lori", "louis", "louise", "lucas", "lynn", "madison", "margaret",
  "maria", "marie", "marilyn", "marjorie", "mark", "martha", "martin", "mary", "mason", "matthew",
  "megan", "melissa", "michael", "michelle", "mike", "mildred", "nancy", "natalie", "nathan",
  "nicholas", "nicole", "noah", "norma", "norman", "olivia", "pamela", "patricia", "patrick", "paul",
  "paula", "peter", "philip", "phillip", "phyllis", "rachel", "ralph", "randy", "raymond", "rebecca",
  "richard", "rita", "robert", "robin", "rodney", "roger", "ronald", "rose", "roy", "ruby", "russell",
  "ruth", "ryan", "samantha", "samuel", "sandra", "sara", "sarah", "scott", "sean", "shannon",
  "sharon", "shawn", "shirley", "sophia", "stacy", "stephanie", "stephen", "steve", "steven", "sue",
  "susan", "tammy", "taylor", "teresa", "terry", "theresa", "thomas", "tiffany", "timothy", "tina",
  "todd", "tom", "tony", "travis", "tyler", "victor", "victoria", "vincent", "virginia", "walter",
  "wanda", "wayne", "wendy", "william", "willie", "zachary"
]);

export const clinicalAnchorWords = new Set([
  "absolute", "albumin", "alk", "alkaline", "anion", "antibiotic", "anticoagulation", "arterial",
  "ast", "atypical", "autoimmune", "basophils", "base", "bicarbonate", "bilirubin", "blood", "bun", "burr",
  "calcium", "cardiology", "cbc", "chloride", "comment", "consult", "creatinine", "culture", "dimer",
  "eosinophils", "endocrinology", "esr", "excess", "ferritin", "fibrinogen", "gap", "glucose",
  "heart", "hematocrit", "hematology", "hemoglobin", "hgb", "hypothyroidism", "imaging", "inpatient", "intake",
  "iron", "ketoacidosis", "ketones", "kidney", "lab", "laboratory", "labs", "lactate", "lipase",
  "lymphocytes", "magnesium",
  "medications", "meds", "mental", "microbiology", "monocytes", "morphology", "nausea", "nephrology",
  "neurology", "neutrophils", "note", "oncology", "output", "pathology", "pco2", "ph", "phos",
  "phosphatase", "phosphate", "phosphorus", "platelet", "platelets", "plt", "po2", "polydipsia",
  "polyuria", "potassium",
  // ── Anchor words added from 3,381-note audit ──
  "albuterol", "allergy", "amoxicillin", "asthma", "auscultation", "bronchitis",
  "cardiovascular", "childhood", "colonoscopy", "congestive", "dialysis", "ecg",
  "endoscopy", "exacerbation", "extremities", "fetal", "furosemide", "gabapentin",
  "heart", "hepatitis", "hydrochlorothiazide", "hyperlipidemia", "hypertension",
  "hypothyroidism", "ibuprofen", "institute", "insulin", "lisinopril",
  "neurological", "oxycodone", "penicillin", "pneumonia", "sertraline",
  "sinusitis", "sodium", "transplant", "x-ray", "xray",
  // ── Clinical modifiers as anchors ──
  "acute", "chronic", "probable", "possible", "likely",
  "suspected", "occasional", "persistent", "recurrent",
  "ischemic", "hemorrhagic", "viral", "bacterial",
  "community-acquired", "hospital-acquired",
  "controlled", "uncontrolled", "stable", "unstable",
  "compensated", "decompensated", "progressive",
  "anemia", "dialysis", "heart", "hypertension", "pneumonia",
  "bronchitis", "sinusitis", "exacerbation", "failure",
  "disease", "syndrome", "disorder", "condition",
  "management", "monitoring", "follow-up", "followup",
  "encounter", "visit", "consultation", "assessment",
  "findings", "parameters", "procedures", "procedure",
  "performed", "conducted", "completed", "scheduled",
  "maintenance", "optimization", "consideration",
  "instructions", "prescription", "regimen", "administration",
  "secondary", "serum", "tightness", "organ", "risk",
  "fluoride", "carbonate", "coronavirus", "isophane",
  "pediatric", "session", "renal", "disease", "syndrome",
  "children", "child", "adult", "pediatric",
  "procalcitonin", "protein", "ptt", "pulmonology", "radiology", "rate", "rbc", "renal", "report",
  "respiratory", "reticulated", "reticulocyte", "saturation", "scheduled", "schistocytes", "sodium",
  "studies", "summary", "team", "temperature", "thyroid", "tibc", "total", "toxic", "transferrin",
  "treatment", "triglycerides", "troponin", "tsh", "urine", "vital", "vitals", "warfarin", "wbc"
]);

[
  "expand all", "collapse all", "expand all collapse all", "hospital progress", "hospital progress note",
  "primary cardiology", "primary cardiology service", "primary service", "code status", "full code",
  "cpr full code", "triage rfv", "recommend fu", "recommend fu cbc", "giving ivf", "cr endocrine", "cr. endocrine",
  "ideally bp", "chg bath", "glucose bld", "one-line summary", "no phi"
].forEach((phrase) => nonNameClinicalPhrases.add(phrase));

[
  "a", "all", "bath", "bld", "bp", "chg", "collapse", "cpr", "cr", "expand", "fu", "giving",
  "ideally", "line", "one-line", "primary", "recommend", "rfv", "service", "triage"
].forEach((word) => nonNameClinicalWords.add(word));

[
  "bp", "chg", "endocrine", "fu", "rfv", "triage"
].forEach((word) => clinicalAnchorWords.add(word));

[
  "a/p", "a1c", "aki", "bmp", "breath", "cad", "cbc", "cc", "chest", "chf", "ckd", "cmp", "copd",
  "dka", "ed", "hpi", "icu", "illness", "of", "pain", "pmh", "present", "psh", "ros",
  "shortness", "soap", "sob", "t1dm", "t2dm", "tsh"
].forEach((word) => nonNameClinicalWords.add(word));

[
  "a/p", "a1c", "aki", "bmp", "cad", "cbc", "cc", "chest", "chf", "ckd", "cmp", "copd", "dka",
  "ed", "hpi", "icu", "pmh", "present", "psh", "ros", "shortness", "soap", "sob", "t1dm",
  "t2dm", "tsh"
].forEach((word) => clinicalAnchorWords.add(word));

[
  "on prednisone", "car echo", "add nephrovite", "elevated lipids", "heart attack",
  "dna amplification", "rna amplification", "pcr amplification", "viral dna", "viral rna",
  "please hold on day", "for renal biopsy", "do not", "or hr", "prn route",
  "low blood sugar", "sterile water", "most recent", "high sensitivity", "cannot be determined",
  "virus rna", "parainflu virus", "rhinovirus enterovirus", "renal transplant", "adult complete",
  "qtc calculation", "external hemoglobin", "hemoglobin a1c", "poc hgb", "poc hbg",
  "nucleated rbc", "non-african american", "african american", "vit d", "troponin t",
  "external poc hbg", "see lab tab", "rpt day", "red blood cells", "guided biopsy kidney",
  "car echo adult complete", "a-line", "arterial line", "bg site", "spec site", "high flow",
  "high flow nasal cannula", "nasal cannula", "not performed", "vitamin b", "vitamin b-12",
  "vitamin b-", "collection date", "xr pelvis", "maxillo panorex image by clinic",
  "oral maxillo panorex image by clinic xr", "maxillo panorex", "metal screening",
  "mr clearance", "xr metal screening mr clearance", "ir cv tunneled cath insertion",
  "mr shoulder w", "mr shoulder w wo con", "w wo con", "request for plasma", "request for platelets",
  "results review", "teg platelet aggregation", "platelet aggregation", "teg clotting time",
  "teg fibrinogen activity", "teg coag index", "teg lyse30", "test cup", "plain cup",
  "beta hcg tumor marker", "hcg tumor marker", "tumor marker", "xr hip bilateral pelvis",
  "hip bilateral pelvis", "hip pelvis", "xr femur views", "xr foot min views", "normal fish",
  "banding type", "prelim result", "prelim result normal fish", "source blood",
  "clinical laboratory", "clinical laboratory improvement", "clinical laboratory improvement amendments",
  "xr forearm", "xr hip unilat", "xr knee", "xr lower leg", "xr wrist", "xr wrist min",
  "corr ven", "quantiferon tb gold", "rpr titer", "treponema pallidum", "minimal react",
  "not predicted", "bacterial vaginosis", "microscopic examination", "microscopic examination of urine",
  "cold autoantibody", "tissue examination", "view post intervention", "post intervention",
  "non reactive", "direct coombs", "direct coombs-", "pos lymphs pct", "abs suppressor",
  "poc sat", "poc sars cov", "poc sars cov-", "hcg beta subunit", "creat ratio",
  "a g ratio", "ldl chol calc", "abs helper", "pos lymphs pct", "abs suppressor",
  "xr chest ap", "xr hand", "xr toe", "ct abdomen", "pelvis iv contrast only",
  "ct sinus", "mandible with con", "ct soft tissue neck with", "cta chest", "pe protocol",
  "ir rvsc tib", "peroneal art", "init vsl w", "nm myocardial perfusion pharm stress",
  "pet ct tumor imaging skull", "base to mid t", "car exercise stress portion", "nuc med",
  "hbv s ab", "multi drug resistant gram negative", "surveillance culture", "n gonorrhoeae",
  "quantiferon tb ag minus nil", "routine reflex result", "c glabrata", "hiv ag",
  "hiv genosure prime", "hiv genosure", "mg pdf", "amphetamine qual", "barbiturate screen",
  "benzodiazapine screen", "see final results", "opiate scrn", "oxymorphone ur screen",
  "phencyclidine ur", "amorphous crystals", "dark yellow", "squam epithel", "epithelial cells",
  "renal epithel", "hyaline casts", "crystal cmt", "uric acid", "meprobamate screen urine",
  "o positive", "xr ankle", "peripheral venous", "retic ct", "body fluid culture",
  "ag value", "pocus anes procedure nerve", "fascial plane block",
  "pocus anes procedure nerve or fascial plane block", "base exc art", "base excess ven",
  "hypochromasia slight", "microcytes slight", "group a streptococcus screen",
  "group a streptococcus screen w o reflex", "w o reflex", "xr ankle min views each bilateral",
  "xr foot views each bilateral", "xr hands views each bilateral",
  "car echo agitated saline adult comp", "agitated saline adult comp", "spec gravity",
  "leukocyte esterase", "xr elbow", "ct cervical spine w", "o con", "ct head",
  "ct upper extremity with con", "us soft tissue head", "vas venous duplex le bilat",
  "vas venous duplex ue bilat", "w o con", "head brain", "soft tissue head neck",
  "corrected arterial", "manual diff", "dna assay", "tacrolimus blood", "b negative",
  "k neg", "c neg", "e neg", "o anti-k", "us renal transplant w", "scanned external ekg",
  "cast type", "ref com comments", "hyaline casts", "anti-k", "no day",
  "us guided needle", "subjective objective assessment and plan", "active antimicrobial orders",
  "ivpb mini-bag plus", "mini-bag plus"
].forEach((phrase) => nonNameClinicalPhrases.add(phrase));

[
  "add", "amplification", "attack", "car", "dna", "echo", "lipid", "lipids",
  "biopsy", "day", "do", "for", "hold", "hr", "nephrovite", "not", "on",
  "or", "please", "prednisone", "rna", "route", "sterile", "sugar", "water",
  "sensitivity", "gen", "cannot", "determined", "virus", "parainflu", "rhinovirus",
  "enterovirus", "transplant", "adult", "complete", "qtc", "calculation", "external",
  "hbg", "quant", "log", "interp", "antibody", "antigen", "surface", "core", "rh",
  "abo", "ekg", "ecg", "guided", "duplex", "titer", "tco2", "venous", "cmv", "ebv",
  "bk", "bkv", "hbv", "hcv", "hiv", "sars", "cov", "pcr", "rpt", "detected",
  "reactive", "nonreactive", "non-reactive", "a-line", "arterial", "line", "bg", "site",
  "spec", "ventilator", "fio2", "peep", "resp", "respirations", "tidal", "volume",
  "liter", "flow", "mode", "nasal", "cannula", "performed", "vitamin", "b-12",
  "oral", "maxillo", "panorex", "image", "clinic", "metal", "screening", "mr",
  "clearance", "ir", "cv", "tunneled", "cath", "insertion", "yrs", "wo", "con",
  "right", "left", "shoulder", "plasma", "collection", "pelvis", "by", "w", "b-",
  "results", "teg", "aggregation", "ma", "hcg", "tumor", "marker", "hip", "bilateral",
  "xr", "xray", "view", "views", "femur", "foot", "min", "fish", "banding", "type", "prelim", "source", "axis",
  "appearance", "ketones", "mucus", "plain", "cup", "trace", "small", "clear", "slightly",
  "analyzed", "counted", "karyotyped", "karyotype", "indication", "corr", "ven", "forearm",
  "unilat", "knee", "lower", "leg", "wrist", "clinical", "improvement", "amendments",
  "clia", "fda", "premarket", "investigational", "certified", "quantiferon", "tb", "gold",
  "rpr", "titer", "treponema", "pallidum", "igg", "indeterminate", "minimal", "react",
  "non", "pos", "abs",
  "dolutegravir", "elvitegravir", "raltegravir", "bictegravir", "cabotegravir", "resistance",
  "predicted", "casts", "none", "seen", "bacterial", "vaginosis", "microscopic", "examination",
  "autoantibody", "cold", "direct", "coombs", "coombs-", "c3d", "covid", "covid-19", "cov-", "sat", "o2",
  "subunit", "qual", "creat", "ratio", "g", "chol", "calc", "nih", "helper", "suppressor",
  "lymphs", "pct", "cd", "iv", "contrast", "only", "sinus", "facial", "mandible", "soft",
  "neck", "cta", "pe", "protocol", "rvsc", "tib", "peroneal", "art", "init", "vsl",
  "tla", "nm", "myocardial", "perfusion", "pharm", "stress", "spect", "pet", "skull",
  "base", "mid", "exercise", "portion", "nuc", "med", "intervention", "multi", "drug",
  "resistant", "negative", "gram", "surveillance", "gonorrhoeae", "naa", "minus", "nil",
  "routine", "glabrata", "genosure", "prime", "sm", "tm", "mg", "pdf", "amphetamine",
  "qual", "barbiturate", "benzodiazapine", "final", "opiate", "scrn", "oxycodone",
  "oxymorphone", "phencyclidine", "amorphous", "crystals", "dark", "squam", "epithel",
  "epithelial", "hyaline", "crystal", "cmt", "uric", "acid", "carisoprodol",
  "meprobamate", "screen", "ankle", "ab", "peripheral", "retic", "body", "fluid",
  "pocus", "anes", "procedure", "nerve", "fascial", "plane", "block", "exc",
  "hypochromasia", "microcytes", "slight", "streptococcus", "reflex", "each",
  "hands", "agitated", "saline", "comp", "gravity", "leukocyte", "esterase", "elbow",
  "head", "brain", "extremity", "tissue", "bilat", "ue", "le", "o", "corrected",
  "manual", "diff", "assay", "tacrolimus", "negative", "neg", "anti-k", "anti",
  "ref", "com", "comments", "guided", "needle", "plan", "antimicrobial", "orders",
  "ivpb", "mini-bag", "plus"
].forEach((word) => nonNameClinicalWords.add(word));

[
  "amplification", "attack", "dna", "echo", "lipid", "lipids", "nephrovite",
  "biopsy", "blood", "hr", "prednisone", "renal", "rna", "route", "sugar",
  "sensitivity", "virus", "transplant", "calculation", "hemoglobin", "glucose",
  "ekg", "ecg", "quant", "antibody", "antigen", "pcr", "titer", "site", "ventilator",
  "fio2", "peep", "resp", "flow", "mode", "vitamin", "image", "screening", "clearance",
  "cath", "insertion", "shoulder", "plasma", "teg", "aggregation", "hcg", "tumor",
  "marker", "xr", "xray", "hip", "femur", "foot", "fish", "banding", "prelim", "source", "axis",
  "appearance", "ketones", "mucus", "cup", "karyotype", "cells", "corr", "ven", "forearm",
  "knee", "leg", "wrist", "quantiferon", "rpr", "treponema", "resistance", "casts",
  "vaginosis", "examination", "autoantibody", "coombs", "covid", "sat", "hcg", "creat",
  "ratio", "chol", "helper", "suppressor", "lymphs", "cd", "sinus", "mandible", "cta",
  "protocol", "rvsc", "peroneal", "myocardial", "perfusion", "pet", "skull", "nuc",
  "hbv", "surveillance", "gonorrhoeae", "glabrata", "genosure", "amphetamine",
  "barbiturate", "benzodiazapine", "opiate", "oxymorphone", "phencyclidine", "crystals",
  "epithel", "hyaline", "uric", "meprobamate", "ankle", "peripheral", "retic",
  "fluid", "pocus", "anes", "nerve", "fascial", "block", "exc", "hypochromasia",
  "microcytes", "streptococcus", "reflex", "agitated", "saline", "gravity",
  "leukocyte", "esterase", "elbow", "head", "brain", "extremity", "tissue",
  "bilat", "corrected", "manual", "diff", "assay", "tacrolimus", "anti-k",
  "comments", "guided", "needle", "plan", "antimicrobial", "ivpb"
].forEach((word) => clinicalAnchorWords.add(word));

export const protectedClinicalAcronyms = new Set([
  "a/p", "a1c", "aki", "bmp", "cad", "cbc", "cc", "chf", "ckd", "cmp", "copd", "dka",
  "doe", "ed", "hpi", "icu", "pmh", "psh", "ros", "soap", "sob", "t1dm", "t2dm", "tsh"
]);

export const promptHeadingWords = new Set([
  "high", "priority", "verify", "before", "rounds", "possible", "dose", "or", "safety",
  "concerns", "missed", "held", "unexpected", "administrations", "questions", "to", "ask",
  "team", "nursing", "likely", "okay", "no", "action", "needed", "phi", "review", "details"
]);

export const promptHeadingAnchorWords = new Set([
  "priority", "rounds", "safety", "concerns", "administrations", "questions", "nursing",
  "missed", "held", "unexpected", "okay", "action", "phi"
]);

export const appGeneratedSourceLabelPattern =
  /^(?:de[-\s]?identified|redacted|translated|scrubbed)\s+(?:soap|source|patient|clinical|chart|note|text|preview|message|context)(?:\s+(?:note|text|preview|context))?$/i;

export const broadNonPhiLocationWords = new Set([
  "india"
]);

export const medicationSaltOrFormWords = new Set([
  "acetate", "bromide", "calcium", "chloride", "citrate", "extended", "fumarate", "hcl",
  "hydrochloride", "injection", "lactate", "magnesium", "oral", "potassium", "sodium", "succinate",
  "sulfate", "tartrate", "tablet", "topical"
]);

export const medicationNameWords = new Set([
  "acetaminophen", "amlodipine", "aspirin", "atorvastatin", "azithromycin", "cefazolin", "cefepime",
  "ceftriaxone", "duloxetine", "enoxaparin", "escitalopram", "furosemide", "gabapentin", "heparin", "hydromorphone",
  "insulin", "levothyroxine", "lisinopril", "losartan", "metformin", "metoprolol", "ondansetron",
  "oxycodone", "pantoprazole", "pregabalin", "senna", "tamsulosin", "tramadol", "trazodone",
  "vancomycin", "warfarin"
]);
["nephrovite", "prednisone"].forEach((word) => medicationNameWords.add(word));

// Medications found missing by 3,381-note audit
[
  "albuterol", "amoxicillin", "ibuprofen", "sertraline", "hydrochlorothiazide",
  "penicillin", "amoxicillin-clavulanate", "montelukast", "fluticasone",
  "budesonide", "ipratropium", "salmeterol", "formoterol", "tiotropium",
  "cetirizine", "loratadine", "fexofenadine", "diphenhydramine",
  "dextromethorphan", "guaifenesin", "benzonatate", "pseudoephedrine",
  "nitrofurantoin", "trimethoprim", "sulfamethoxazole", "clindamycin",
  "doxycycline", "azithromycin", "cephalexin", "cefdinir", "cefuroxime",
  "mupirocin", "nystatin", "clotrimazole", "terbinafine", "fluconazole",
  "acyclovir", "valacyclovir", "oseltamivir", "metronidazole",
  "levofloxacin", "ciprofloxacin", "moxifloxacin", "gentamicin",
  "insulin glargine", "insulin lispro", "insulin aspart", "insulin regular",
  "glipizide", "glyburide", "glimepiride", "pioglitazone",
  "sitagliptin", "empagliflozin", "dapagliflozin", "semaglutide",
  "liraglutide", "methimazole", "propylthiouracil",
  "alendronate", "ibandronate", "risedronate", "calcitonin",
  "docusate", "senna", "polyethylene glycol", "lactulose",
  "loperamide", "bismuth", "sucralfate", "mesalamine",
  "allopurinol", "febuxostat", "colchicine", "probenecid",
  "methotrexate", "hydroxychloroquine", "azathioprine",
  "mycophenolate", "tacrolimus", "cyclosporine",
  "carbidopa", "levodopa", "pramipexole", "ropinirole",
  "donepezil", "memantine", "rivastigmine", "galantamine",
  "lamotrigine", "levetiracetam", "topiramate", "valproic",
  "carbamazepine", "oxcarbazepine", "phenytoin", "phenobarbital",
  "lacosamide", "zonisamide", "ethosuximide",
  "fluoxetine", "paroxetine", "citalopram", "venlafaxine",
  "desvenlafaxine", "bupropion", "mirtazapine", "trazodone",
  "aripiprazole", "quetiapine", "olanzapine", "risperidone",
  "haloperidol", "clozapine", "lurasidone", "lithium",
  "alprazolam", "lorazepam", "diazepam", "clonazepam",
  "temazepam", "eszopiclone", "zolpidem", "buspirone",
  "hydralazine", "clonidine", "doxazosin", "terazosin",
  "carvedilol", "labetalol", "propranolol", "bisoprolol",
  "digoxin", "amiodarone", "flecainide", "sotalol",
  "nitroglycerin", "isosorbide", "hydralazine",
  "ezetimibe", "fenofibrate", "gemfibrozil", "niacin",
  "pravastatin", "simvastatin", "rosuvastatin", "lovastatin",
  "candesartan", "telmisartan", "olmesartan", "irbesartan",
  "valsartan", "losartan", "enalapril", "ramipril", "benazepril",
  "captopril", "lisinopril",
  "verapamil", "diltiazem", "nifedipine", "amlodipine",
  "celecoxib", "diclofenac", "indomethacin", "ketorolac", "meloxicam",
  "naproxen", "cyclobenzaprine", "methocarbamol", "baclofen", "tizanidine",
  "sumatriptan", "rizatriptan", "eletriptan",
  "folic acid", "cyanocobalamin", "ergocalciferol", "cholecalciferol",
  "ferrous sulfate", "ferrous gluconate", "iron sucrose",
  "potassium chloride", "magnesium oxide", "calcium carbonate",
  "sodium bicarbonate", "sodium chloride",
  "epinephrine", "naloxone", "flumazenil", "protamine",
  "phytonadione", "vitamin k", "protamine sulfate",
  // Brand-name medications that look like regular words (high-risk for name misclassification)
  "celebrex", "prozac", "zoloft", "paxil", "xanax", "valium", "ativan", "klonopin",
  "ambien", "lunesta", "sonata", "adderall", "ritalin", "vyvanse", "concerta",
  "lexapro", "celexa", "effexor", "cymbalta", "pristiq", "remeron", "wellbutrin",
  "abilify", "seroquel", "zyprexa", "risperdal", "geodon", "latuda",
  "lipitor", "crestor", "zocor", "pravachol", "vytorin", "zetia",
  "norvasc", "cardizem", "procardia", "toprol", "coreg", "tenormin",
  "lasix", "bumex", "demadex", "apresoline",
  "coumadin", "plavix", "eliquis", "xarelto", "pradaxa", "brilinta",
  "nexium", "prilosec", "protonix", "aciphex", "prevacid", "pepcid", "zantac",
  "zofran", "phenergan", "reglan", "compazine",
  "vicodin", "norco", "percocet", "oxycontin", "dilaudid", "fentanyl", "ultram",
  "motrin", "aleve", "celebrex", "voltaren", "mobic",
  "singulair", "advair", "spiriva", "symbicort", "pulmicort",
  "januvia", "farxiga", "ozempic", "trulicity", "mounjaro", "rybelsus",
  "synthroid", "cytomel", "armour",
  "glucophage", "actos", "amaryl", "glyburide",
  "vasotec", "cozaar", "diovan", "benicar", "micardis", "avapro",
  "xalatan", "restasis", "pataday", "patanol", "lumigan",
  "cresemba", "diflucan", "lamisil", "sporanox",
  "zithromax", "bactrim", "augmentin", "bicillin", "rocephin", "zosyn", "avelox",
  "neurontin", "lyrica", "tegretol", "dilantin", "keppra", "topamax", "depakote",
  "ultram", "darvocet", "stadol", "suboxone", "methadone",
  "imodium", "colace", "miralax", "gas-x", "pepto-bismol",
  "flonase", "afrin", "claritin", "allegra", "zyrtec", "benadryl", "patanase",
  "viagra", "cialis", "levitra", "stendra",
  "propecia", "rogaine", "latisse", "botox",
  "actonel", "boniva", "fosamax", "reclast", "prolia", "forteo",
  "eriacta", "plan b", "ella", "mirena", "skyla", "paragard", "nuvaRing",
  "keflex", "omnicef", "rocephin", "invanz",
  "zestril", "accupril", "altace", "univasc", "mavik",
].forEach((word) => medicationNameWords.add(word));

export const clinicalInstructionWords = new Set([
  "add", "do", "for", "hold", "not", "on", "or", "please", "prn", "route",
  "resume", "start", "stop", "continue", "discontinue", "give", "take",
  "titrate", "increase", "decrease", "reduce", "maintain", "administer",
  "begin", "keep", "restart", "switch", "change", "convert", "transition",
  "prescribe", "prescribed", "recommend", "recommended", "order", "ordered",
  "required", "needed", "suggest", "suggested", "indicated", "use", "using",
  "consider", "considering", "initiate", "initiated", "provide", "provided",
  "dispense", "dispensed", "supply", "supplied", "instruct", "instructed",
  "advise", "advised", "counsel", "counseled", "educated", "education",
  "direct", "directed", "need", "needs", "require", "requires"
]);

export const clinicalInstructionAnchorWords = new Set([
  "biopsy", "blood", "day", "hr", "renal", "route", "sugar", "water"
]);

export const medicationClassOrStemPattern = /(?:^cef|cillin$|cycline$|floxacin$|mycin$|azole$|avir$|pril$|sartan$|olol$|dipine$|statin$|parin$|prazole$|tidine$|zepam$|zolam$|azepam$|azide$|semide$|thiazide$|gliflozin$|gliptin$|tide$|caine$|sone$|mab$|nib$)/i;
export const honorificPatternSource = String.raw`(?:Mr|Mrs|Ms|Miss|Mx|Dr|Doctor|Prof|Professor)`;
export const patientHonorificPatternSource = String.raw`(?:Mr|Mrs|Ms|Miss|Mx)`;
export const nameWordPatternSource = String.raw`[A-Z][A-Za-z.'-]{1,}`;
export const namePartPatternSource = String.raw`(?:${nameWordPatternSource}|[A-Z]\.?)`;
export const fullNamePatternSource = String.raw`${namePartPatternSource}(?:[ \t]+${namePartPatternSource}){1,4}`;
export const titledNamePatternSource = String.raw`${honorificPatternSource}\.?\s+${namePartPatternSource}(?:[ \t]+${namePartPatternSource}){0,4}`;
export const suffixPattern = /^(?:jr|sr|ii|iii|iv|v)$/i;
export const credentialPattern = /^(?:md|do|np|pa-c|pa|rn|pharmd|phd)$/i;

export const doseUnitPattern = /\b\d+\s*(?:mg|mcg|micrograms?|grams?|g|mL|ml|units?|IU|mEq|milliequivalents?|mmol|mmol\/L|meq\/L|mg\/dL|mcg\/mL|mg\/kg|mg\/m2)\b/gi;
export const doseFormPattern = /\b\d+\s*(?:mg|mcg|micrograms?|grams?|g)\s+(?:po|PO|iv|IV|subcut|subcutaneous|sublingual|buccal|topical|inhaled|nebulized|intramuscular|rectal|vaginal)\b/gi;

export function isLikelyMedicationContext(text) {
  return doseUnitPattern.test(text) || doseFormPattern.test(text) ||
    /(?:take|give|administer|prescribe|dispense|order|refill|supply)\s+(?:\d+\s*(?:mg|mcg|g|mL|units?|tablets?|capsules?))\b/i.test(text) ||
    /\b(?:tab|tablet|capsule|cap|injection|syrup|suspension|elixir|solution|cream|ointment|gel|patch|spray|inhaler|drop|suppository)\b(?:\s*\d+\s*(?:mg|mcg|g|mL))?\b/i.test(text);
}

